# Generated by Django 5.1.7 on 2025-03-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0002_match_round_number_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default=('available', 'Available'), max_length=10),
        ),
    ]
