# Generated by Django 5.1.7 on 2025-03-31 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0003_tournament_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='registered_tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
