# Generated by Django 5.1.7 on 2025-03-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0004_tournament_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='users',
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='num_teams_registered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='available', max_length=10),
        ),
    ]
