# Generated by Django 5.1.7 on 2025-03-31 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0005_remove_team_user_remove_tournament_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='registered_tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
