# Generated by Django 5.1.7 on 2025-03-31 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0006_tournament_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='max_teams',
        ),
    ]
